/* Illustrative concept pieces, not real inventory or items offered for sale. */
window.RJ_PIECES = [
 {id:'aabha-kundan',name:'Aabha Kundan Collar',category:'Kundan',occasion:'Wedding',tone:'Gold',mood:'Regal',description:'A sculptural collar inspired by Rajasthan’s ceremonial ornamentation. An exploration in symmetry, light and layered gemstones.',details:'Concept exploration · Kundan-inspired · Statement collar',image:'photo-1617038220319-276d3cfab638',tag:'Signature study'},
 {id:'gul-meenakari',name:'Gul Meenakari Drops',category:'Meenakari',occasion:'Festive',tone:'Gold',mood:'Expressive',description:'Colour, miniature detailing and enamel traditions imagined as an expressive pair of occasion earrings.',details:'Concept exploration · Enamel-inspired · Drop earrings',image:'photo-1630019852942-f89202989a59',tag:'Colour study'},
 {id:'noor-polki',name:'Noor Polki Choker',category:'Polki',occasion:'Wedding',tone:'Gold',mood:'Regal',description:'An imagined heirloom silhouette with bold proportions and softly luminous stonework.',details:'Concept exploration · Polki-inspired · Choker',image:'photo-1599643478518-a784e5dc4c8f',tag:'Editorial favourite'},
 {id:'tara-silver',name:'Tara Silver Cuffs',category:'Silver',occasion:'Everyday',tone:'Silver',mood:'Minimal',description:'Everyday silver forms borrowing geometry from carved jharokha windows and the desert horizon.',details:'Concept exploration · Silver-inspired · Wristwear',image:'photo-1611652022419-a9419f74343d',tag:'Everyday study'},
 {id:'surya-kundan',name:'Surya Kundan Pendant',category:'Kundan',occasion:'Festive',tone:'Gold',mood:'Minimal',description:'A more delicate interpretation of ornate heritage jewellery, made for modern festive dressing.',details:'Concept exploration · Kundan-inspired · Pendant',image:'photo-1515562141207-7a88fb7ce338',tag:'Modern heritage'},
 {id:'chand-polki',name:'Chand Polki Earrings',category:'Polki',occasion:'Festive',tone:'Gold',mood:'Regal',description:'Moonlit forms and historic Rajasthan patterns guide a dramatic earring concept.',details:'Concept exploration · Polki-inspired · Earrings',image:'photo-1535632066927-ab7c9ab60908',tag:'Heritage study'},
 {id:'sitara-silver',name:'Sitara Silver Ring',category:'Silver',occasion:'Everyday',tone:'Silver',mood:'Minimal',description:'Clean lines, a quiet focal point and an understated design language for everyday wear.',details:'Concept exploration · Silver-inspired · Ring',image:'photo-1605100804763-247f67b3557e',tag:'Understated'},
 {id:'rang-meenakari',name:'Rang Meenakari Cuff',category:'Meenakari',occasion:'Festive',tone:'Gold',mood:'Expressive',description:'A vibrant motif study informed by the painted palaces and enamel artistry of Jaipur.',details:'Concept exploration · Enamel-inspired · Cuff',image:'photo-1602173574767-37ac01994b2a',tag:'Colour study'},
 {id:'meher-kundan',name:'Meher Kundan Set',category:'Kundan',occasion:'Wedding',tone:'Gold',mood:'Expressive',description:'Layers of ornament reinterpreted with a sense of movement and warmth for celebratory styling.',details:'Concept exploration · Kundan-inspired · Jewellery set',image:'photo-1626784215021-2e39ccf971cd',tag:'Ceremony study'},
 {id:'shyam-silver',name:'Shyam Silver Pendant',category:'Silver',occasion:'Everyday',tone:'Silver',mood:'Expressive',description:'Traditional texture distilled into a simple statement for everyday wardrobes.',details:'Concept exploration · Silver-inspired · Pendant',image:'photo-1611085583191-a3b181a88401',tag:'Contemporary'},
 {id:'raahi-polki',name:'Raahi Polki Ring',category:'Polki',occasion:'Wedding',tone:'Gold',mood:'Minimal',description:'An imagined modern heirloom ring where a single striking form carries the story.',details:'Concept exploration · Polki-inspired · Ring',image:'photo-1608042314453-ae338d80c427',tag:'Statement study'},
 {id:'pankh-meenakari',name:'Pankh Meenakari Pendant',category:'Meenakari',occasion:'Everyday',tone:'Gold',mood:'Expressive',description:'Featherlike forms and rich palettes translate heritage enamel work into a fresh everyday concept.',details:'Concept exploration · Enamel-inspired · Pendant',image:'photo-1631982690223-8aa4be0a2497',tag:'Playful study'}
];
window.RJ_IMG = (id, width=900) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=82`;
