from pathlib import Path
from html import escape
root=Path(__file__).parent
nav=[('Home','index.html'),('Discover','discover.html'),('The Studio','studio.html'),('Our Story','story.html'),('Technology','technology.html')]

def header(active):
    links=''.join(f'<a href="{url}" class="{"active" if label==active else ""}" {"aria-current=page" if label==active else ""}>{label}</a>' for label,url in nav)
    return f'''<a class="skip-link" href="#main">Skip to content</a>
<div class="announcement">A NEW PERSPECTIVE ON HERITAGE <b>✦</b> THE RAJASTHAN JEWELS CONCEPT STUDIO IS OPEN</div>
<header class="site-header"><div class="wrap header-inner">
<button class="menu-toggle" id="menu-toggle" aria-controls="mobile-menu" aria-expanded="false" aria-label="Open navigation">☰</button>
<nav class="desktop-nav" aria-label="Main navigation">{links}</nav>
<a class="brand" href="index.html" aria-label="Rajasthan Jewels home"><img class="brand-icon" src="assets/monogram.svg" width="42" height="42" alt=""><div><div class="brand-name">Rajasthan Jewels</div><div class="brand-small">THE HERITAGE STUDIO</div></div></a>
<div class="header-actions"><a class="studio-link" href="contact.html">Get in touch <span class="arrow">↗</span></a><a href="discover.html?saved=1" aria-label="View saved pieces">Saved <span class="saved-count" data-saved-count>0</span></a></div>
</div><nav class="mobile-menu" id="mobile-menu" aria-label="Mobile navigation">{links}<a href="contact.html">Contact</a></nav></header>'''

def footer():
    return '''<footer class="footer"><div class="wrap"><div class="footer-inner">
<div class="footer-about"><a href="index.html" class="brand" aria-label="Rajasthan Jewels home"><img class="brand-icon" src="assets/monogram.svg" alt="" width="42" height="42"><div><div class="brand-name">Rajasthan Jewels</div><div class="brand-small">THE HERITAGE STUDIO</div></div></a><p>An independent, early-stage project imagining a more personal way to discover Indian jewellery. Inspired by Rajasthan, designed for what's next.</p><span class="small-ornament" aria-hidden="true">✧</span></div>
<div><h4>Explore</h4><a href="discover.html">Concept collection</a><a href="studio.html">Style Finder</a><a href="story.html">Our Story</a><a href="technology.html">Technology roadmap</a></div>
<div><h4>Information</h4><a href="contact.html">Contact</a><a href="privacy.html">Privacy</a><a href="discover.html?saved=1">Your saved pieces</a><a href="https://unsplash.com/license" target="_blank" rel="noopener noreferrer">Photography licence ↗</a></div>
<div><h4>Begin a conversation</h4><p>For feedback, collaboration or early access to the project.</p><a class="contact-row" href="contact.html">Write to the studio ↗</a><p style="font-size:11px">Jaipur-inspired · Made for the world</p></div>
</div><div class="footer-lower"><span>© <span id="current-year">2026</span> Rajasthan Jewels. Concept-stage startup.</span><span class="disclaimer">Editorial imagery is illustrative, not photographs of merchandise. No products are currently offered for sale on this site.</span></div></div></footer>
<div class="sr-only" role="status" aria-live="polite" id="live-status"></div>'''

def page(file,title,description,active,body):
    head=f'''<!doctype html><html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(title)} | Rajasthan Jewels</title><meta name="description" content="{escape(description,quote=True)}"><meta name="theme-color" content="#17362d"><meta name="color-scheme" content="light">
<link rel="icon" href="assets/monogram.svg" type="image/svg+xml"><link rel="canonical" href="https://rajasthanjewels.com/{'' if file=='index.html' else file}">
<meta property="og:type" content="website"><meta property="og:site_name" content="Rajasthan Jewels"><meta property="og:title" content="{escape(title,quote=True)} | Rajasthan Jewels"><meta property="og:description" content="{escape(description,quote=True)}"><meta property="og:url" content="https://rajasthanjewels.com/{'' if file=='index.html' else file}"><meta property="og:image" content="https://rajasthanjewels.com/assets/og.svg"><meta name="twitter:card" content="summary_large_image">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="preconnect" href="https://images.unsplash.com"><link rel="stylesheet" href="styles.css">
<script type="application/ld+json">{{"@context":"https://schema.org","@type":"WebSite","name":"Rajasthan Jewels","url":"https://rajasthanjewels.com","description":"Heritage-inspired jewellery discovery concept startup."}}</script>
<script src="data.js" defer></script><script src="app.js" defer></script></head><body data-page="{file.removesuffix('.html')}">'''
    (root/file).write_text(head+header(active)+'<main id="main">'+body+'</main>'+footer()+'</body></html>',encoding='utf-8')

pic=lambda photo,width=1000:f'https://images.unsplash.com/{photo}?auto=format&amp;fit=crop&amp;w={width}&amp;q=82'

home=f'''<section class="hero" aria-labelledby="hero-heading"><div class="hero-copy"><span class="eyebrow light">THE NEXT CHAPTER OF HERITAGE</span><h1 id="hero-heading">A heritage,<br><em>reimagined.</em></h1><p>Inspired by the rich jewellery traditions of Rajasthan. A new digital studio where artistry, personal style and thoughtful technology come together.</p><a class="button light" href="discover.html">Explore the concept collection <span class="arrow">↗</span></a><span class="hero-index">01 / HERITAGE, RECONSIDERED</span></div>
<div class="hero-photo" id="hero-photo"><img src="{pic('photo-1617038220319-276d3cfab638',1300)}" alt="Gold jewellery editorial photograph" fetchpriority="high"><div class="photo-caption">Imagery for inspiration only / Not inventory</div></div></section>
<div class="wrap"><div class="intro-strip"><span>Inspired by Rajasthan</span><span>A more personal discovery</span><span>Thoughtfully digital</span></div></div>
<section class="section" aria-labelledby="intro-heading"><div class="wrap intro-grid"><div class="intro-image"><img loading="lazy" src="{pic('photo-1599643478518-a784e5dc4c8f')}" alt="Jewellery in a warm editorial setting"></div><div class="intro-copy"><span class="eyebrow">THE IDEA</span><h2 id="intro-heading">Yesterday's beauty.<br><em>Tomorrow's experience.</em></h2><p>Rajasthan's jewellery traditions carry generations of design knowledge: the colour of meenakari, the radiance of kundan, the character of silver. Our vision is to make discovering these styles feel as personal as wearing them.</p><p>We're building an early-stage discovery experience that begins with design inspiration and grows toward a more intelligent, approachable way to explore jewellery.</p><a class="button text-button" href="story.html">Explore our story <span class="arrow">↗</span></a><div class="quote-detail"><strong>RJ</strong><span>Rooted in the past.<br>Curious about the future.</span></div></div></div></section>
<section class="section collections" aria-labelledby="collections-heading"><div class="wrap"><div class="section-head"><div><span class="eyebrow">AN INTRODUCTION TO THE ART FORMS</span><h2 id="collections-heading">Discover the <em>traditions.</em></h2></div><p>Four beautiful traditions. Endless possibilities. Our early visual studies explore their different moods and languages.</p></div>
<div class="collections-grid"><a class="collection-card" href="discover.html?category=Kundan"><img loading="lazy" src="{pic('photo-1515562141207-7a88fb7ce338')}" alt="Gold jewellery inspired by Kundan"><div class="collection-info"><span>01 / GOLD & LIGHT</span><h3>Kundan</h3><span class="link">Explore concepts <span class="arrow">↗</span></span></div></a>
<a class="collection-card" href="discover.html?category=Polki"><img loading="lazy" src="{pic('photo-1535632066927-ab7c9ab60908')}" alt="Statement jewellery inspired by Polki"><div class="collection-info"><span>02 / THE HEIRLOOM MOOD</span><h3>Polki</h3><span class="link">Explore concepts <span class="arrow">↗</span></span></div></a>
<a class="collection-card" href="discover.html?category=Meenakari"><img loading="lazy" src="{pic('photo-1630019852942-f89202989a59')}" alt="Ornamental jewellery inspired by Meenakari"><div class="collection-info"><span>03 / COLOUR & CRAFT</span><h3>Meenakari</h3><span class="link">Explore concepts <span class="arrow">↗</span></span></div></a></div></div></section>
<section class="section" aria-labelledby="selected-heading"><div class="wrap"><div class="section-head"><div><span class="eyebrow">FROM THE CONCEPT ARCHIVE</span><h2 id="selected-heading">Objects of <em>inspiration.</em></h2></div><a class="button text-button" href="discover.html">View all concepts <span class="arrow">↗</span></a></div><div class="product-grid" id="featured-pieces" aria-live="polite"></div></div></section>
<section class="statement"><div class="wrap statement-inner"><div><span class="eyebrow light">MEET THE DISCOVERY STUDIO</span><h2>Heritage has a story.<br><em>Your style has one too.</em></h2></div><div class="statement-aside"><span class="number">PERSONALISED / 01</span><p>Try our interactive style finder to see which traditions and concept pieces match your mood. It's a working first step toward our planned Claude-powered jewellery concierge.</p><a class="button light" href="studio.html">Find your style <span class="arrow">↗</span></a></div></div></section>
<section class="editorial"><div class="editorial-photo"><img loading="lazy" src="{pic('photo-1602173574767-37ac01994b2a',1100)}" alt="Jewellery photographed with soft warm tones"></div><div class="editorial-content"><span class="eyebrow">WE'RE JUST BEGINNING</span><h2>Built with a sense<br>of <em>possibility.</em></h2><p>We're at the concept-and-prototype stage. We don't claim to have a live jewellery inventory or an AI service running yet. What we do have is a direction: a digital experience that makes finding meaningful jewellery easier and more inspiring.</p><a class="button outline" href="technology.html">See what we're building <span class="arrow">↗</span></a></div></section>'''
page('index.html','Heritage, Reimagined','Discover Rajasthan Jewels, an early-stage jewellery discovery studio inspired by Rajasthani design and intelligent personalisation.','Home',home)

discover='''<section class="page-hero" aria-labelledby="catalog-title"><div class="wrap"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a><span>/</span>Concept collection</nav><span class="eyebrow">THE DIGITAL DESIGN ARCHIVE</span><h1 id="catalog-title">A world of <em>detail.</em></h1><p>Explore illustrative jewellery concepts inspired by Rajasthan’s most expressive traditions. Save the styles you love, then discover more through our Style Finder.</p></div></section>
<section class="catalog-section"><div class="wrap"><div class="catalog-toolbar"><label class="catalog-search"><span aria-hidden="true">⌕</span><span class="sr-only">Search concepts</span><input id="catalog-search" type="search" placeholder="Search a style, name or occasion…" autocomplete="off"></label><label><span class="sr-only">Sort collection</span><select class="select" id="catalog-sort"><option value="featured">Featured</option><option value="az">Name A–Z</option><option value="za">Name Z–A</option></select></label></div><div class="catalog-filters" role="group" aria-label="Filter by jewellery tradition"><button class="filter-btn" data-category="All" aria-pressed="true">All traditions</button><button class="filter-btn" data-category="Kundan" aria-pressed="false">Kundan</button><button class="filter-btn" data-category="Polki" aria-pressed="false">Polki</button><button class="filter-btn" data-category="Meenakari" aria-pressed="false">Meenakari</button><button class="filter-btn" data-category="Silver" aria-pressed="false">Silver</button><button class="filter-btn" data-category="Saved" aria-pressed="false">♡ Saved pieces</button><span class="filter-count" id="catalog-count"></span></div><div class="product-grid" id="catalog-grid" aria-live="polite"></div><p class="catalog-disclosure">Please note: The names and descriptions above are original design concepts. Photographs are third-party editorial references and may not depict the described concept piece. They are not product listings or offers for sale; pricing, stock, metal purity and fulfilment are not available at this stage.</p></div></section>'''
page('discover.html','Discover the Concept Collection','Browse Kundan, Polki, Meenakari and silver-inspired jewellery concepts in the Rajasthan Jewels digital discovery studio.','Discover',discover)

studio='''<section class="page-hero slim"><div class="wrap"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a><span>/</span>Style Studio</nav><span class="eyebrow">INTERACTIVE PROTOTYPE / 01</span><h1>Your story, <em>your style.</em></h1><p>An invitation to explore what feels like you. Answer three questions and we'll curate styles from our concept archive.</p></div></section><section><div class="wrap studio-grid"><div class="studio-intro"><span class="eyebrow">THE STYLE FINDER</span><h2>Let's find what<br><em>speaks to you.</em></h2><p>Great design should feel personal. This is our first working tool for matching your mood and occasion with Rajasthani jewellery traditions.</p><div class="studio-note"><strong>How it works today:</strong> recommendations are generated locally with transparent, rule-based matching. A conversational experience using Claude is on our product roadmap; no AI API is currently connected.</div></div><div class="quiz-panel"><p class="overline">YOUR STYLE PORTRAIT / THREE QUESTIONS</p>
<div class="quiz-group"><h3>01. What's the occasion?</h3><div class="quiz-options" role="group" aria-label="Occasion"><button class="quiz-choice" data-group="occasion" data-value="Everyday" aria-pressed="false">Everyday elegance</button><button class="quiz-choice" data-group="occasion" data-value="Festive" aria-pressed="false">A celebration</button><button class="quiz-choice" data-group="occasion" data-value="Wedding" aria-pressed="false">A special ceremony</button></div></div>
<div class="quiz-group"><h3>02. How would you describe your style?</h3><div class="quiz-options" role="group" aria-label="Style mood"><button class="quiz-choice" data-group="mood" data-value="Minimal" aria-pressed="false">Quietly refined</button><button class="quiz-choice" data-group="mood" data-value="Regal" aria-pressed="false">Timeless & regal</button><button class="quiz-choice" data-group="mood" data-value="Expressive" aria-pressed="false">Bold & expressive</button></div></div>
<div class="quiz-group"><h3>03. Which finish calls to you?</h3><div class="quiz-options" role="group" aria-label="Metal colour"><button class="quiz-choice" data-group="tone" data-value="Gold" aria-pressed="false">Warm gold</button><button class="quiz-choice" data-group="tone" data-value="Silver" aria-pressed="false">Cool silver</button><button class="quiz-choice" data-group="tone" data-value="Any" aria-pressed="false">I'm open to both</button></div></div>
<div class="quiz-actions"><button class="button" id="discover-match" disabled>Discover my style <span class="arrow">↗</span></button><span class="hint" id="quiz-hint">Choose one answer for each question</span></div><div id="studio-results" class="studio-results" hidden aria-live="polite"></div></div></div></section>'''
page('studio.html','The Style Finder','Find your jewellery inspiration with the Rajasthan Jewels interactive style finder and explore our personalised discovery roadmap.','The Studio',studio)

story=f'''<section class="page-hero"><div class="wrap"><nav class="breadcrumbs"><a href="index.html">Home</a><span>/</span>Our Story</nav><span class="eyebrow">ROOTED IN RAJASTHAN</span><h1>Tradition in our eyes.<br><em>Tomorrow in our hands.</em></h1><p>An independent startup idea that begins with respect for craft and a belief that discovering jewellery can feel more human.</p></div></section>
<section><div class="wrap story-feature"><div class="story-image"><img loading="lazy" src="{pic('photo-1515562141207-7a88fb7ce338')}" alt="Delicate jewellery photographed as editorial inspiration"></div><div class="story-copy"><span class="eyebrow">THE BEGINNING</span><h2>A new way to<br><em>discover old beauty.</em></h2><p>Rajasthan is a place of extraordinary artistic languages—from the jewel-bright palettes of enamel work to the delicate geometry of traditional ornaments. These forms deserve to be explored with curiosity, context and care.</p><p>Rajasthan Jewels is a new, independently developed digital discovery concept. We're starting small: a beautifully designed archive, thoughtful recommendations and an honest roadmap for an AI-assisted experience.</p><p>We are not claiming a workshop, artisans, certified products or an operating jewellery store. Those relationships, product sourcing and commerce infrastructure would need to be established as the venture develops.</p></div></div></section>
<section class="principles"><div class="wrap"><div class="section-head"><div><span class="eyebrow">WHAT GUIDES THE WORK</span><h2>Three things we <em>believe.</em></h2></div></div><div class="principle-grid"><div class="principle"><span class="num">01</span><h3>Craft before noise.</h3><p>We want to help people appreciate the history and material language behind jewellery rather than reducing every piece to a trend.</p></div><div class="principle"><span class="num">02</span><h3>Personal, not generic.</h3><p>Discovery should reflect the person and the moment, whether that's a quiet everyday detail or a celebration that matters.</p></div><div class="principle"><span class="num">03</span><h3>Technology with care.</h3><p>Digital tools should simplify choice, explain their recommendations and make room for human judgement.</p></div></div></div></section>
<section class="statement"><div class="wrap statement-inner"><div><span class="eyebrow light">THE NEXT CHAPTER</span><h2>Curiosity builds the<br><em>most beautiful futures.</em></h2></div><div class="statement-aside"><p>Want to offer feedback, collaborate on the product, or follow the first public release? We'd love to hear from you.</p><a class="button light" href="contact.html">Contact the founder <span class="arrow">↗</span></a></div></div></section>'''
page('story.html','Our Story','The story behind Rajasthan Jewels, an independent early-stage jewellery discovery project rooted in traditional Indian design.','Our Story',story)

tech='''<section class="page-hero"><div class="wrap"><nav class="breadcrumbs"><a href="index.html">Home</a><span>/</span>Technology</nav><span class="eyebrow">PRODUCT & ENGINEERING</span><h1>A thoughtful way<br><em>forward.</em></h1><p>What we're building, what's real today, and how we plan to introduce Claude as the product evolves.</p></div></section>
<section><div class="wrap tech-intro"><span class="eyebrow">THE PRODUCT VISION</span><h2>Artistry meets <em>intelligence.</em></h2><p>We envision a more useful jewellery exploration platform: one that helps people discover styles, articulate preferences and understand heritage craft, with clear explanations rather than black-box suggestions.</p></div><div class="wrap feature-cards"><article class="feature-card"><span class="feature-icon">01</span><h3>Explore beautifully.</h3><p>A searchable, filterable concept archive with saved favourites and item details. Available today in the live prototype.</p><div class="status">✓ Implemented</div></article><article class="feature-card"><span class="feature-icon">02</span><h3>Discover personally.</h3><p>A simple rule-based style matcher considers occasion, aesthetic and finish, showing why suggested styles fit. Available today.</p><div class="status">✓ Implemented</div></article><article class="feature-card"><span class="feature-icon">03</span><h3>Converse naturally.</h3><p>Planned Claude-powered assistant to answer style questions, discuss cultural context and refine preferences using natural language.</p><div class="status">○ Planned, not deployed</div></article></div></section>
<section class="roadmap"><div class="wrap"><span class="eyebrow light">A TRANSPARENT DEVELOPMENT ROADMAP</span><h2>The roadmap, <em>not the hype.</em></h2><div class="roadmap-grid"><div class="roadmap-step"><small>Phase 01 / Now</small><h3>Public prototype</h3><p>Responsive site, design-system foundation, concept catalogue, local saved items and a working style quiz. All client-side; no accounts or payment processing.</p></div><div class="roadmap-step"><small>Phase 02 / Planned</small><h3>Claude concierge</h3><p>Introduce a secured server-side Anthropic API integration for conversational styling, multilingual assistance, and explanations. API credentials would never be exposed in the browser.</p></div><div class="roadmap-step"><small>Phase 03 / Future</small><h3>Real catalogue</h3><p>Integrate authorised supplier information, accurate product photography, inventory management and transaction infrastructure—only after sourcing and compliance are in place.</p></div></div></div></section>
<section class="section"><div class="wrap intro-grid"><div><span class="eyebrow">TECHNICAL PRINCIPLE</span><h2>Design for trust,<br><em>build for change.</em></h2><p>Our first version is intentionally simple: a fast, accessible static frontend, original concept data, browser-only favourites and an explainable recommendation algorithm. No personal account or behavioural tracking is required to try the experience.</p><a class="button outline" href="studio.html">Try the working prototype <span class="arrow">↗</span></a></div><div style="background:var(--pine);padding:65px 50px;color:#f6efdd;min-height:360px;position:relative;overflow:hidden"><img src="assets/floral.svg" alt="" style="position:absolute;opacity:.12;inset:-10%;width:120%;height:120%"><div style="position:relative"><span class="eyebrow light">BUILD WITH INTENTION</span><h3 style="font-size:clamp(43px,5vw,69px);margin:38px 0 16px">Human taste.<br><em>Better tools.</em></h3><p style="color:#d1dccf">The experience we're creating.</p></div></div></div></section>'''
page('technology.html','Our Technology Roadmap','Explore the Rajasthan Jewels MVP, working rule-based style finder, and planned server-side Claude AI concierge integration.','Technology',tech)

contact='''<section class="page-hero slim"><div class="wrap"><nav class="breadcrumbs"><a href="index.html">Home</a><span>/</span>Contact</nav><span class="eyebrow">LET'S CONNECT</span><h1>Good things begin<br>with <em>conversation.</em></h1><p>Have a thought, collaboration idea or early interest? Send a note.</p></div></section>
<section><div class="wrap contact-grid"><div class="contact-copy"><span class="eyebrow">REACH THE STUDIO</span><h2>We'd love to<br><em>hear from you.</em></h2><p>This project is in its early stages. Your feedback on the design, product idea or the experience itself helps shape what we build next.</p><div class="contact-details"><span class="overline">PROPOSED STARTUP MAILBOX</span><a href="mailto:hello@rajasthanjewels.com">hello@rajasthanjewels.com</a><p style="font-size:11px">Note: this mailbox must be configured on the domain before messages can be received.</p></div></div><div class="contact-form"><form id="contact-form"><div class="form-row"><div class="field"><label for="contact-name">Your name *</label><input id="contact-name" name="name" maxlength="120" required autocomplete="name" placeholder="Your name"></div><div class="field"><label for="contact-email">Email address *</label><input id="contact-email" name="email" type="email" maxlength="254" required autocomplete="email" placeholder="you@example.com"></div></div><div class="field"><label for="contact-topic">What brings you here?</label><select id="contact-topic" name="topic"><option>General enquiry</option><option>Product feedback</option><option>Collaboration</option><option>Early access interest</option></select></div><div class="field"><label for="contact-message">Your message *</label><textarea id="contact-message" name="message" maxlength="3000" minlength="10" required placeholder="Tell us a little about your idea…"></textarea></div><button class="button" type="submit">Prepare email <span class="arrow">↗</span></button><p class="form-caption">This demo doesn't have a backend inbox. Submitting opens your own email application with the details filled in; nothing is uploaded from this form.</p><p id="contact-message-status" class="form-alert" role="status">Your email app should open. If not, please manually email hello@rajasthanjewels.com once that address is configured.</p></form></div></div></section>'''
page('contact.html','Contact the Studio','Get in touch with Rajasthan Jewels to offer product feedback, discuss collaboration, or express early access interest.','',contact)

privacy='''<section class="page-hero slim"><div class="wrap"><nav class="breadcrumbs"><a href="index.html">Home</a><span>/</span>Privacy</nav><span class="eyebrow">INFORMATION & PRIVACY</span><h1>Simple by <em>design.</em></h1><p>What this prototype does—and doesn't—collect.</p></div></section><div class="wrap"><article class="content-prose"><p><strong>Last updated:</strong> October 8, 2026. This policy describes the Rajasthan Jewels concept-stage website. It will be updated when new services are introduced.</p><h2>1. Information stored on your device</h2><p>Saved items are stored locally in your browser using <code>localStorage</code> under the key <code>rj-saved</code>. The style quiz works in your browser and does not transmit your answers to any server. You can clear saved items using your browser's site-data controls.</p><h2>2. Contact form</h2><p>The contact form prepares an email using your device's email client. It does not directly send the information to our servers or store form submissions. Any email you choose to send will be handled by your email provider and the recipient's provider.</p><h2>3. Third-party resources</h2><p>The site uses Google Fonts and Unsplash-hosted imagery. Loading those resources may share technical request information such as your IP address with the respective providers under their own privacy practices. The site does not implement Google Analytics, advertising trackers or remarketing tags.</p><h2>4. Payments and accounts</h2><p>This prototype has no account creation, checkout, payment collection or order processing. Concept items are not available for purchase.</p><h2>5. Future updates</h2><p>If we later introduce a Claude-powered assistant, user accounts or mailing-list sign-up, we will revise this policy and disclose what information is transmitted and retained before activating those services.</p><h2>6. Questions</h2><p>For questions about the project or this policy, use the <a href="contact.html" style="text-decoration:underline">contact page</a>. The proposed domain mailbox requires configuration before it can receive email.</p></article></div>'''
page('privacy.html','Privacy Policy','Read how the Rajasthan Jewels prototype handles saved styles, the style finder, third-party assets, and contact forms.','',privacy)

piece='''<section class="wrap"><nav class="breadcrumbs" style="margin-top:36px" aria-label="Breadcrumb"><a href="index.html">Home</a><span>/</span><a href="discover.html">Concept collection</a><span>/</span><span id="piece-breadcrumb">Concept detail</span></nav><div class="piece-layout" id="piece-container"><div class="piece-image image-fallback"></div><div class="piece-info"><span class="eyebrow">THE CONCEPT ARCHIVE</span><h1>Loading concept…</h1></div></div></section><section class="section collections"><div class="wrap"><div class="section-head"><div><span class="eyebrow">MORE INSPIRATION</span><h2>More to <em>discover.</em></h2></div></div><div class="product-grid" id="related-pieces"></div></div></section>'''
page('piece.html','Concept Detail','An illustrative Rajasthan Jewels concept piece with design inspirations and similar styles to explore.','Discover',piece)

notfound='''<section class="page-hero"><div class="wrap" style="text-align:center"><span class="eyebrow">A WRONG TURN</span><h1>Not quite the <em>right path.</em></h1><p style="margin:0 auto 35px">The page you're looking for may have moved. There's plenty to discover back at the studio.</p><a href="index.html" class="button">Return home <span class="arrow">↗</span></a></div></section>'''
page('404.html','Page Not Found','This Rajasthan Jewels page could not be found. Return to the home page to keep exploring.','',notfound)
print('Generated:', ', '.join(sorted(p.name for p in root.glob('*.html'))))
